export const POMODORO_STUDY_MINUTES = 50;
export const POMODORO_BREAK_MINUTES = 10;
export const POMODORO_CYCLES = 3;

export const POMODORO_STUDY_SECONDS = POMODORO_STUDY_MINUTES * 60;
export const POMODORO_BREAK_SECONDS = POMODORO_BREAK_MINUTES * 60;

export const POMODORO_TOTAL_MINUTES =
  POMODORO_CYCLES * (POMODORO_STUDY_MINUTES + POMODORO_BREAK_MINUTES);
